Complete all tasks for Lab#1
bodkiny/nure-cross-platform-programming pull request #1
Opened 2024-02-26 21:12 UTC by bodkiny

## Created the required classes and implemented them according to the task description. Covered all classes with unit tests with 100% line coverage.

![image](https://github.com/bodkiny/nure-cross-platform-programming/assets/124298580/ff2218dd-a23d-4305-96ce-9dbe2dd6fba3)

### Libraries used:
- 'org.junit.jupiter:junit-jupiter-api:5.10.2';
- 'org.junit.jupiter:junit-jupiter-engine:5.10.2';
- 'org.projectlombok:lombok:1.18.30'.

### Plugins:
- 'org.apache.maven.plugins:maven-surefire-plugin:3.2.5';
- 'org.jacoco:jacoco-maven-plugin:0.8.11'.

2024-03-04 17:24 UTC, kdimak requested changes
First impression: really good! I left small remarks from what the most important one is to split `SortingNumbers` class into two.

2024-03-04 17:24 UTC, kdimak commented on lab1/src/main/java/ua/nure/cpp/lab1/computations/SortingNumbers.java
> +        try (Scanner sc = new Scanner(System.in)) {
I recommend splitting this class into 2. One class will just sort the numbers. The second one will be responsible for the data input. For now, `SortingNumbers` violates [SRP](https://en.wikipedia.org/wiki/Single_responsibility_principle) because there're 2 reasons to change the class:
1) change the source of input;
2) change the sorting algorithm.

2024-03-04 17:24 UTC, kdimak commented on lab1/src/main/java/ua/nure/cpp/lab1/oop/ComplexNumber.java
> +@EqualsAndHashCode
Try to use just [@Value](https://projectlombok.org/features/Value) annotation of Lombok.

2024-03-04 17:24 UTC, kdimak commented on lab1/src/main/java/ua/nure/cpp/lab1/oop/ComplexNumber.java
> +    public static ComplexNumber add(ComplexNumber a, ComplexNumber b) {
Look at `BigDecimal` API: this class is also immutable but it provides non-static API like:
```
   ComplexNumber n1 = new ComplexNumber(1, 2);
   ComplexNumber sum = n1.add(new ComplexNumber(3, 4));
```

2024-03-04 17:24 UTC, kdimak commented on lab1/src/test/java/ua/nure/cpp/lab1/computations/SortingNumbersTest.java
> +class SortingNumbersTest {
Maybe [Parametrized Tests ](https://www.baeldung.com/parameterized-tests-junit-5)can be used to provide different kinds of inputs/outputs you want to validate?

2024-03-04 17:24 UTC, kdimak commented on lab1/src/test/java/ua/nure/cpp/lab1/oop/PointTest.java
> +    void testDistanceToOrigin() {
A general recommendation: you can skip a `test` prefix of the test function names. Having `@Test` annotation is enough for JUnit to identify test routines.

2024-03-04 17:24 UTC, kdimak commented on lab1/src/test/java/ua/nure/cpp/lab1/strings/StringFromBinaryTreeTest.java
> +    @Disabled("Disabled due to method implementation")
There should be a reason why you haven't removed the disabled test. Probably it makes sense just to drop this test.

2024-03-11 13:39 UTC, kdimak commented on lab1/src/test/java/ua/nure/cpp/lab1/computations/TaskProcessorTest.java
> +        System.setIn(in);
This assignment is not needed.

2024-03-11 13:39 UTC, kdimak commented on lab1/src/test/java/ua/nure/cpp/lab1/computations/TaskProcessorTest.java
> +        return Stream.of(
Good!

2024-03-11 13:39 UTC, kdimak approved these changes

2024-03-11 14:30 UTC, bodkiny commented on lab1/src/test/java/ua/nure/cpp/lab1/computations/TaskProcessorTest.java
> +        System.setIn(in);
I forgot to remove it. It stayed after I attempted to initialize the `System.in` input stream in the `ConsoleArrayReader` constructor without parameters. But in that case, the `System.setIn()` method wasn't working for some reason.

2024-03-11 14:31 UTC, merged